name: CI

on:
  push:
    branches:
    - master
    - release/*
  workflow_dispatch:

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
      env:
        REACT_APP_REDIRECT_URI: ${{ secrets.REACT_APP_REDIRECT_URI }}
        REACT_APP_SPOTIFY_CLIENT_ID: ${{ secrets.REACT_APP_SPOTIFY_CLIENT_ID }}
    - run: cd client && yarn install
    - run: |
          cd client
          touch .env.production
          echo REACT_APP_REDIRECT_URI =${{ secrets.REACT_APP_REDIRECT_URI }} >> .env.production
          echo REACT_APP_SPOTIFY_CLIENT_ID =${{ secrets.REACT_APP_SPOTIFY_CLIENT_ID }} >> .env.production
          cat .env.production
    - run: cd client && REACT_APP_REDIRECT_URI =${{ secrets.REACT_APP_REDIRECT_URI }} REACT_APP_SPOTIFY_CLIENT_ID =${{ secrets.REACT_APP_SPOTIFY_CLIENT_ID }} yarn run build
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}